param(
    [switch]$Run,
    [string]$OutputPath = "dist\AssistenteGLAB.ps1"
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$outputFullPath = Join-Path $projectRoot $OutputPath
$outputDir = Split-Path -Parent $outputFullPath

New-Item -ItemType Directory -Path $outputDir -Force | Out-Null

$script = Get-Content -LiteralPath (Join-Path $projectRoot "WinTool.ps1") -Raw

$header = @"
# Assistente G-LAB compiled script
# Generated by Compile.ps1
# Source repository: https://github.com/mrmatias-of/assistente-glab

"@

Set-Content -LiteralPath $outputFullPath -Value ($header + $script) -Encoding UTF8

Write-Host "Compiled: $outputFullPath"

if ($Run) {
    powershell.exe -NoProfile -STA -ExecutionPolicy Bypass -File $outputFullPath
}
